=== cbenzola/xml_project/schemas/athleteSchema.xsd
<?xml version="1.0" encoding="utf-8"?>

<!--
   
   Final Project
   
   Filename: athleteSchema.xsd
   Author: Chris Benzola
   Date:   04/28/2019
-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="name" type="xs:string"/>
    <xs:element name="team" type="xs:string"/>
    <xs:element name="image" type="xs:string"/>
    <xs:element name="year" type="xs:short"/>
    <xs:element name="hits" type="xs:byte"/>
    <xs:element name="homeruns" type="xs:byte"/>
    <xs:element name="average" type="xs:float"/>
    <xs:element name="onbase" type="xs:float"/>
    <xs:element name="war" type="xs:float"/>
    <xs:element name="athlete">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="team"/>
                <xs:element ref="image"/>
                <xs:element ref="year"/>
                <xs:element ref="hits"/>
                <xs:element ref="homeruns"/>
                <xs:element ref="average"/>
                <xs:element ref="onbase"/>
                <xs:element ref="war"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="athletes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="athlete" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cbenzola/xml_project/xml/athletes.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
   
   Final Project
   
   Filename: athletes.xml
   Author: Chris Benzola
   Date:   04/28/2019
-->



<?xml-stylesheet type="text/xsl" href="../xsl/athletes.xsl" ?> <!-- include athlete stylesheet -->

<athletes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="file:///C:/Users/cbenz/OneDrive/Desktop/XML_Final/schemas/athleteSchema.xsd"> <!-- athlete schema -->
	
<athlete>
	<name>Aaron Judge</name>
	<team>New York Yankees</team>
	<image>../images/aaronJudge.jpg</image>
	<!-- Information For Stat Table -->
	<year>2019</year>
	<atBats>73</atBats>
		<hits>21</hits>
		<homeruns>5</homeruns>
		<average>.288</average>
		<onbase>.404</onbase>
		<war>1.2</war>
	
	</athlete>
	
	<athlete>
	<name>Mike Trout</name>
		<!-- Information For Stat Table -->
		<atBats>103</atBats>
	<team>LA Angels</team>
	<image>../images/trout.jpg</image>
	
	<year>2019</year>
		<hits>30</hits>
		<homeruns>6</homeruns>
		<average>.303</average>
		<onbase>.492</onbase>
		<war>2.5</war>
	
	</athlete>
	
	<athlete>
	<name>Joey Votto</name>
	<team>Cincinatti Reds</team>
	<image>../images/votto.jpg</image>
	<!-- Information For Stat Table -->
	<year>2019</year>
		<atBats>119</atBats>
		<hits>26</hits>
		<homeruns>3</homeruns>
		<average>.235</average>
		<onbase>.342</onbase>
		<war>0.2</war>
	
	</athlete>
	
	<athlete>
	<name>Mookie Betts</name>
	<team>Boston Red Sox</team>
	<image>../images/betts.jpg</image>
	<!-- Information For Stat Table -->
	<year>2019</year>
		<atBats>134</atBats>
		<hits>39</hits>
		<homeruns>6</homeruns>
		<average>.297</average>
		<onbase>.399</onbase>
		<war>1.5</war>
	
	</athlete>
	
	
</athletes>
